# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AppCarros' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppCarros

pod "Alamofire"
pod "SDWebImage"

  target 'AppCarrosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppCarrosUITests' do
    # Pods for testing
  end

end
